In [9]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [10]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [11]:
x_df = df.drop('price',axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [12]:
y_df=df['price']
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [13]:
# Create linear regression object
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [14]:
lr.coef_

array([135.78767123])

In [15]:
lr.intercept_

180616.43835616432

In [16]:
### pickle file

In [17]:
import pickle

In [18]:
with open("lr_model",'wb') as file:
    pickle.dump(lr,file)

In [19]:
#### Load Saved Model

In [20]:
with open('lr_model','rb') as file:
    mp = pickle.load(file)

In [21]:
mp.coef_

array([135.78767123])

In [22]:
mp.intercept_

180616.43835616432

In [23]:
mp.predict([[5000]])

array([859554.79452055])

In [24]:
###create a file named sample.json with some data:
import json

sampleJson = {
    "name": "Luminar",
    "place": "Kochi",
    "phonenumber":"8714135828"
}

json_object = json.dumps(sampleJson)


In [25]:
json_object

'{"name": "Luminar", "place": "Kochi", "phonenumber": "8714135828"}'

In [26]:
with open("sample.json","w") as file:
    file.write(json_object)

In [27]:
with open("sample.json","r") as file:
    newdata = json.load(file)

In [28]:
newdata

{'name': 'Luminar', 'place': 'Kochi', 'phonenumber': '8714135828'}

In [29]:
#### Save trained model using Joblib

In [30]:
import joblib 

In [31]:
joblib.dump(lr,'model_joblib_new')

['model_joblib_new']

In [32]:
mj = joblib.load('model_joblib_new')

In [33]:
mj.coef_

array([135.78767123])

In [34]:
mj.intercept_

180616.43835616432

In [35]:
joblib.load('lr_model')

LinearRegression()